name: E2E Test

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  test:
    name: Run E2E Tests
    runs-on: ubuntu-latest
    environment: E2E
    env:
      E2E_SECRET: ${{ secrets.E2E_SECRET }}
      E2E_TOKEN: ${{ secrets.E2E_TOKEN }}
      E2E_UNIVAPAY_ADMIN_EMAIL: ${{ secrets.E2E_UNIVAPAY_ADMIN_EMAIL }}
      E2E_UNIVAPAY_ADMIN_PASSWORD: ${{ secrets.E2E_UNIVAPAY_ADMIN_PASSWORD }}
      E2E_UNIVAPAY_ADMIN_CONSOLE_URL: ${{ vars.E2E_UNIVAPAY_ADMIN_CONSOLE_URL }}
      E2E_API_URL: ${{ vars.E2E_API_URL }}
      E2E_WIDGET_URL: ${{ vars.E2E_WIDGET_URL }}
      E2E_FORMURL: ${{ vars.E2E_FORMURL }}
      E2E_CAPTURE: yes

    steps:
    - uses: actions/checkout@v4

    - name: Setup Environment
      uses: ./.github/workflows/common
      with:
        php-version: '8.2'

    - name: Run Docker Compose
      run: WP_PORT=80 docker compose up -d

    - name: Run E2E Tests Block Checkout
      run: |
        docker compose exec wp /bin/bash -c "cd /var/www/html/wp-content/plugins/UnivaPay-for-WooCommerce && composer init:e2e && npm run test:e2e:block"

    - name: Run E2E Tests Classic Checkout
      run: |
        docker compose exec wp /bin/bash -c "cd /var/www/html/wp-content/plugins/UnivaPay-for-WooCommerce && composer init:e2e && ./bin/wc-checkout-change-layout.sh && npm run test:e2e:classic"
